export const supportedCountries = [
  { value: "us", label: "United States" },
  { value: "gb", label: "United Kingdom" },
  { value: "au", label: "Australia" },
  { value: "ca", label: "Canada" },
  { value: "de", label: "Germany" },
  { value: "es", label: "Spain" },
  { value: "fr", label: "France" },
  { value: "it", label: "Italy" },
  { value: "nl", label: "Netherlands" },
  { value: "ru", label: "Russia" },
  { value: "se", label: "Sweden" },
  { value: "tr", label: "Turkey" },
  { value: "ae", label: "United Arab Emirates" },
  { value: "ar", label: "Argentina" },
  { value: "at", label: "Austria" },
  { value: "be", label: "Belgium" },
  { value: "br", label: "Brazil" },
  { value: "ch", label: "Switzerland" },
  { value: "cl", label: "Chile" },
  { value: "co", label: "Colombia" },
  { value: "cz", label: "Czech Republic" },
  { value: "dk", label: "Denmark" },
  { value: "fi", label: "Finland" },
  { value: "gr", label: "Greece" },
  { value: "hk", label: "Hong Kong" },
  { value: "hu", label: "Hungary" },
  { value: "ie", label: "Ireland" },
  { value: "in", label: "India" },
  { value: "is", label: "Iceland" },
  { value: "jp", label: "Japan" },
  { value: "kr", label: "South Korea" },
];

export const showTypes = [
  { value: "all", label: "All" },
  { value: "movie", label: "Movie" },
  { value: "series", label: "Series" },
];
export const languageShow = [
  { value: "", label: "All" },
  { value: "en", label: "English" },
  { value: "sp", label: "Spanish" },
  { value: "fr", label: "French" },
  { value: "de", label: "German" },
  { value: "it", label: "Italian" },
  { value: "ru", label: "Russian" },
  { value: "zh", label: "Chinese" },
  { value: "ja", label: "Japanese" },
  { value: "ko", label: "Korean" },
  { value: "ar", label: "Arabic" },
  { value: "hi", label: "Hindi" },
];

export const genresShow = [
  { value: "", label: "All" },
  { value: 1, label: "Biography" },
  { value: 10402, label: "Music" },
  { value: 10749, label: "Romance" },
  { value: 10751, label: "Family" },
  { value: 10752, label: "War" },
  { value: 10763, label: "News" },
  { value: 10764, label: "Reality" },
  { value: 10767, label: "Talk Show" },
  { value: 12, label: "Adventure" },
  { value: 14, label: "Fantasy" },
  { value: 16, label: "Animation" },
  { value: 18, label: "Drama" },
  { value: 2, label: "Film Noir" },
  { value: 27, label: "Horror" },
  { value: 28, label: "Action" },
  { value: 3, label: "Game Show" },
  { value: 35, label: "Comedy" },
  { value: 36, label: "History" },
  { value: 37, label: "Western" },
  { value: 4, label: "Musical" },
  { value: 5, label: "Sport" },
  { value: 53, label: "Thriller" },
  { value: 6, label: "Short" },
  { value: 7, label: "Adult" },
  { value: 80, label: "Crime" },
  { value: 878, label: "Science Fiction" },
  { value: 9648, label: "Mystery" },
  { value: 99, label: "Documentary" },
];
